'use strict';
/*
 * ezone-managers server — fully open read-only dashboard.
 *
 *   - NO password, NO login screen, NO access key and NO session cookie.
 *     Anyone who opens the URL gets the whole app, including the patient
 *     names in each house's entry/exit log. That is a deliberate decision
 *     by the app owner (September 12, 2026); see docs/open-access.md.
 *   - fail-closed startup (APPS_SCRIPT_URL required in production)
 *   - per-IP rate limiting on /api/sheets, so the open proxy cannot be used
 *     to drain the shared Apps Script quota
 *   - security headers incl. X-Robots-Tag: noindex, nofollow
 *   - APPS_SCRIPT_URL is server-to-server only; it is never sent to a browser
 *     and never echoed in an error body.
 *   - lib/ is NOT statically mounted; only bonus-eligibility.js is exposed
 */
const express = require('express');
const path = require('path');

const PORT = Number(process.env.PORT) || 3000;
const APPS_SCRIPT_URL = process.env.APPS_SCRIPT_URL || '';
const IS_PROD = process.env.NODE_ENV === 'production';

function fatal(msg) {
  console.error(`[fatal] ${msg}`);
  process.exit(1);
}

// Fail closed in production. Tests require() this module with NODE_ENV=test.
if (process.env.NODE_ENV !== 'test' && require.main === module) {
  if (!APPS_SCRIPT_URL) fatal('APPS_SCRIPT_URL is required');
}

const app = express();
app.disable('x-powered-by');
// Behind Railway's proxy: without this, req.ip is the proxy's IP for ALL
// users, so the rate limit becomes one shared bucket for everyone.
app.set('trust proxy', 1);
app.use(express.json({ limit: '16kb' }));

// ---- security headers (every response) ----
app.use((req, res, next) => {
  // The app is open but it is still an internal tool: keep it out of every
  // search index. robots.txt says the same thing for crawlers that read it.
  res.setHeader('X-Robots-Tag', 'noindex, nofollow');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('X-Frame-Options', 'DENY');
  res.setHeader('Referrer-Policy', 'no-referrer');
  res.setHeader(
    'Content-Security-Policy',
    [
      "default-src 'self'",
      "script-src 'self'",
      // inline style attributes are generated by the chart render paths
      "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
      "font-src 'self' https://fonts.gstatic.com",
      "img-src 'self' data:",
      "connect-src 'self'",
      "frame-ancestors 'none'",
      "base-uri 'none'",
      "form-action 'none'",
      "object-src 'none'"
    ].join('; ')
  );
  if (IS_PROD) {
    res.setHeader('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
  }
  next();
});

// ---- per-IP rate limiting ----
function makeRateLimiter({ windowMs, max }) {
  const hits = new Map();
  function allow(ip) {
    const now = Date.now();
    // Sweep expired buckets so a long-running process cannot grow unbounded.
    if (hits.size > 5000) {
      for (const [k, v] of hits) if (now > v.resetAt) hits.delete(k);
    }
    const entry = hits.get(ip) || { count: 0, resetAt: now + windowMs };
    if (now > entry.resetAt) {
      entry.count = 0;
      entry.resetAt = now + windowMs;
    }
    entry.count++;
    hits.set(ip, entry);
    return entry.count <= max;
  }
  allow.clear = () => hits.clear();
  return allow;
}

function clientIp(req) {
  return req.ip || (req.socket && req.socket.remoteAddress) || 'unknown';
}

// The app polls the overview every 60s and fetches up to 6 house payloads on
// first paint, so the limit is generous — it exists to cap abuse of the open
// proxy, not to ration normal use.
const allowSheets = makeRateLimiter({ windowMs: 15 * 60 * 1000, max: 300 });

// ---- static: public assets only (no gate — the app is open) ----
app.use(express.static(path.join(__dirname, 'public')));

// Expose ONLY the client-shared bonus module. There is no static mount on
// lib/, so nothing else under it is reachable over HTTP.
app.get('/lib/bonus-eligibility.js', (_req, res) => {
  res.setHeader('Cache-Control', 'no-cache');
  res.sendFile(path.join(__dirname, 'lib', 'bonus-eligibility.js'));
});

app.get('/healthz', (_req, res) => res.json({ ok: true, ts: Date.now() }));

// ---- Apps Script proxy ----
const ALLOWED_QUERY_KEYS = new Set(['action', 'house', 'month']);

app.get('/api/sheets', async (req, res) => {
  if (!allowSheets(clientIp(req))) {
    return res.status(429).json({ error: 'יותר מדי בקשות. נסו שוב מאוחר יותר.' });
  }
  try {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(req.query)) {
      if (ALLOWED_QUERY_KEYS.has(k) && typeof v === 'string') qs.set(k, v);
    }
    const s = qs.toString();
    const target = `${APPS_SCRIPT_URL}${s ? `?${s}` : ''}`;

    const upstream = await fetch(target, {
      method: 'GET',
      redirect: 'follow',
      headers: { Accept: 'application/json' }
    });

    const text = await upstream.text();
    res.status(upstream.status);
    res.set('Cache-Control', 'no-store');
    const ct = upstream.headers.get('content-type') || 'application/json';
    res.type(ct).send(text);
  } catch (err) {
    // Log the detail, return none: a URL-parse failure would otherwise echo
    // APPS_SCRIPT_URL straight to the browser.
    console.error('Proxy error:', err && err.message);
    res.status(502).json({ error: 'upstream_error' });
  }
});

// ---- 404 for unknown /api routes (before SPA fallback) ----
app.use('/api', (_req, res) => res.status(404).json({ error: 'not found' }));

// ---- SPA fallback ----
app.get('*', (_req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

if (require.main === module) {
  app.listen(PORT, '0.0.0.0', () => {
    console.log(`ezone-managers listening on 0.0.0.0:${PORT}`);
  });
}

module.exports = { app, _rateLimiters: { allowSheets } };
